# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 08:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_area', models.CharField(max_length=20, verbose_name='Voters Must Be From')),
                ('start_time', models.DateTimeField(verbose_name='Start Time')),
                ('end_time', models.DateTimeField(verbose_name='End Time')),
                ('poll_type', models.CharField(max_length=6, verbose_name='Poll Type')),
                ('title', models.CharField(max_length=40, verbose_name='Poll Title')),
                ('question', models.CharField(max_length=240, verbose_name='Poll Question')),
                ('values', models.CharField(max_length=300, verbose_name='Poll Answers')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100, verbose_name='Choice')),
                ('poll_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Poll')),
            ],
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employment', models.CharField(max_length=2, verbose_name='Employment Status')),
                ('age_band', models.CharField(max_length=2, verbose_name='Age Band')),
                ('constituency', models.CharField(max_length=30, verbose_name='Constituency')),
                ('gender', models.CharField(max_length=1, verbose_name='Gender')),
                ('last_login', models.DateTimeField(verbose_name='Last Login Time')),
            ],
        ),
        migrations.AddField(
            model_name='vote',
            name='voter_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Voter'),
        ),
    ]
