# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voter',
            name='constituency',
        ),
        migrations.AddField(
            model_name='poll',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Approved'),
        ),
        migrations.AddField(
            model_name='voter',
            name='country',
            field=models.CharField(default='United Kingdom', max_length=30, verbose_name='Country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voter',
            name='local_area',
            field=models.CharField(default='Ilford North', max_length=30, verbose_name='Local Area'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='voter',
            name='age_band',
            field=models.CharField(max_length=1, verbose_name='Age Band'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='employment',
            field=models.CharField(max_length=1, verbose_name='Employment Status'),
        ),
    ]
